name: Run Laravel Tests

on:
  push:
    branches:
      - main  # Or your default branch (e.g., master, dev)
  pull_request:
    branches:
      - main  # Runs when a pull request is created for the main branch

jobs:
  test:
    runs-on: ubuntu-latest  # Defines the runner operating system

    steps:
      # Checkout code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up PHP environment
      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'  # Change to your desired PHP version
          extensions: mbstring, xml, bcmath, mysql, curl  # Add other PHP extensions as needed

      # Install Composer dependencies
      - name: Install Composer dependencies
        run: |
          composer install --no-interaction --prefer-dist

      # Set up environment variables for testing
      - name: Set up .env.testing file
        run: |
          cp .env.example .env
          echo "APP_ENV=testing" >> .env
          echo "DB_CONNECTION=mysql" >> .env
          echo "DB_DATABASE=homestead" >> .env  # Set this to your test database
          echo "DB_USERNAME=root" >> .env
          echo "DB_PASSWORD=" >> .env

      # Run database migrations
      - name: Run database migrations
        run: php artisan migrate --env=testing

      # Run Laravel tests
      - name: Run tests
        run: php artisan test --env=testing

      # Cache dependencies for faster builds (optional)
      - name: Cache Composer dependencies
        uses: actions/cache@v2
        with:
          path: vendor
          key: ${{ runner.os }}-composer-${{ hashFiles('**/composer.lock') }}
          restore-keys: |
            ${{ runner.os }}-composer-
